export const canvasHeight = 32 * 18;
export const canvasWidth = 32 * 32;
export const playerHeight = 246;
export const latMovementSpeed = 250;
export const baseGravity = 9.8 * 90;
export const megaGravity = baseGravity * 2.5;
export const jumpVelocity = -360;
export const scale = 2;
export const playerScale = 1
